function [scenario, egoVehicle] = scenario01_straight_highway_lead_vehicle()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 25.2 (R2025b) and Automated Driving Toolbox 25.2 (R2025b).
% Generated on: 04-Aug-2026 22:52:10

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    250 0 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'StraightHighway');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [20.0 -1.80 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'EgoVehicle');
waypoints = [20.0 -1.8 0.01;
    240 -1.8 0];
speed = [25;25];
waittime = [0;0];
trajectory(egoVehicle, waypoints, speed, waittime);

% Add the non-ego actors
leadVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [80 -1.8 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'LeadVehicle');
waypoints = [80 -1.8 0;
    240 -1.8 0];
speed = [20;20];
waittime = [0;0];
trajectory(leadVehicle, waypoints, speed, waittime);

